### ISSUE TITLE
The file "stereo_pinhole.yaml" is missing

### ISSUE THREAD

**Issue by genhh** [tub-rip/dvs_mcemvs#2]
There is an error running the MVSEC-related configuration file, so what is the format of **"stereo_pinhole.yaml"**?

```
#command:
roscd mapper_emvs_stereo/
cd cfg/upenn_mvsec/mvsec_flying1_full/AcAt/
rosrun mapper_emvs_stereo run_emvs --flagfile=flying1.conf
```
ERROR:
terminate called after throwing an instance of 'YAML::BadFile'
  what():  bad file: stereo_pinhole.yaml
*** Aborted at 1724292533 (unix time) try "date -d @1724292533" if you are using GNU date ***
PC: @     0x7faf7d57be87 gsignal
*** SIGABRT (@0x3e800002c03) received by PID 11267 (TID 0x7faf804006c0) from PID 11267; stack trace: ***
    @     0x7faf7ea1a980 (unknown)
    @     0x7faf7d57be87 gsignal
    @     0x7faf7d57d7f1 abort
    @     0x7faf7dbf1646 (unknown)
    @     0x7faf7dc02f06 (unknown)
    @     0x7faf7dc02f71 std::terminate()
    @     0x7faf7dc031b4 __cxa_throw
    @     0x55ab8a5e8252 (unknown)
    @     0x7faf7e39f077 get_camera_calib_yaml_mvsec()
    @     0x55ab8a5d4202 (unknown)
    @     0x7faf7d55ec87 __libc_start_main
    @     0x55ab8a5d5e6a (unknown)
Aborted (core dumped)

**Comment by genhh** [comment]
I tried to construct the "stereo_pinhole.yaml" file in reverse from the code in calib.cpp. Here is the format and data for cam0. cam1 is a similar construct and will work if the data is sufficient.
```
cam0:
  resolution: [346,260]
  intrinsics: [226.38018519795807,226.15002947047415,173.6470807871759,133.73271487507847]
  distortion_model: equidistant
  distortion_coeffs: [-0.048031442223833355, 0.011330957517194437, -0.055378166304281135, 0.021500973881459395]
  projection_matrix: 
    - [199.6530123165822, 0.0, 177.43276376280926, 0.0]
    - [0.0, 199.6530123165822, 126.81215684365904, 0.0]
    - [0.0, 0.0, 1.0, 0.0]
  T_cn_cnm0:   
    - [ 0.999877311526236,  0.015019439766575743, -0.004447282784398257,  0.0 ]
    - [-0.014996983873604017, 0.9998748347535599,  0.005040367172759556,  0.0 ]
    - [ 0.004522429630305261, -0.004973052949604937, 0.9999774079320989,  0.0 ]
    - [ 0.0,                 0.0,                 0.0,                 1.0 ]
```
remember add --calib_path=your_path_stereo_pinhole.yaml when you run
